### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#1]
![contact frost finery](https://cloud.githubusercontent.com/assets/383701/9592009/a50371ec-500d-11e5-9bc0-b6636e632bd8.png)

Currently, the footer doesn't stick to the bottom, and it should. We can use flexbox to achieve this: https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

**Comment by frostyweather** [comment]
Close #1. Footer is now stuck to the bottom on each page after using flex box.
