### ISSUE TITLE
Add "Send a Request" Area

### ISSUE THREAD

**Issue by frostyweather** [bradfrost/frost-finery-wp#11]
- Add "Request Custom Order" button to the page
- Add form to the page where user can request custom order
  >Name, Email, Type of Work (Necklace, Earrings, etc.), Budget, Date They Need It By

**Comment by frostyweather** [comment]
Add this to "Custom Work" page and "Contact" page

**Comment by frostyweather** [comment]
Added send request buttons to Custom Work and Contact pages locally. Didn't know where to link this button up, whether it was a Google doc or something else. Thanks.

**Comment by bradfrost** [comment]
We'll make a new issue for creating a contact form.

**Comment by frostyweather** [comment]
Added "Request a Custom Order" Buttons to Contact and Custom Work Page that take you directly to the form on the Contact Page.
