### ISSUE TITLE
jewelry category and attributes

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#12]
• nice to display multiple images, one on white and one someone wearing
• title 
• price
• description
• tags (filter by gold, silver, druzy, etc)
• jewelry category (only suck in pieces tagged custom work or collection or archive)
• optional link to buy in collection (shopify?)
• login state: price, wholesale price, inventory, views

• chunk together jewelry items and then have their different product states? or show multiple pictures of the silver vs gold-plated vs brass version, etc.

**Comment by minifrost** [comment]
Could we please also add white bronze and bronze as materials under the jewelry category? Thank you!

**Comment by frostyweather** [comment]
Just added that to the materials. Should be there now. Thanks.

**Comment by bradfrost** [comment]
These attributes are in Wordpress. We'll make a separate issue for displaying this info.
