### ISSUE TITLE
Instagram blog integration

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#13]
automate instagram feed to link to blog

**Comment by bradfrost** [comment]
https://wordpress.org/plugins/instagrate-to-wordpress/

**Comment by frostyweather** [comment]
Installed the plugin both locally and remotely.
- We need a cURL PHP extension which I am not sure we have with this site. 
- Also, Melissa has to fill in her Instagram information on the [Frost Finery Page](http://frostfinery.com/wp-admin/options-general.php?page=instagratetowordpress).

**Comment by bradfrost** [comment]
I checked to see if we have cURL on the server, and yes we do. I think @minifrost just has to hook up her credentials and she should be good to go.

**Comment by frostyweather** [comment]
Great! Thanks.

**Comment by frostyweather** [comment]
Under the wp-admin, please fill in your instagram credentials, @minifrost . You'll do that under Plugins>Instagrate to Wordpress> Settings and you should be able to fill them out there. Thanks!

**Comment by bradfrost** [comment]
FYI @minifrost I just logged in and connected your Instagram account to your blog. Try posting something and we'll test to see if it's working.

**Comment by minifrost** [comment]
working!

**Comment by frostyweather** [comment]
Does it actually post to the "Blog" page itself on your site Mel? I see your last Instagram post is on your site, but I wasn't sure if you manually copied and pasted it to the blog itself. Let me know. Thanks!

**Comment by minifrost** [comment]
It posted automatically, but I did change the title because my caption from Instagram was so long and that automatically ended up being the title. I'm fine with going in and changing the title. 

One thing is that on mobile the layout is looking a bit off. The old images are full bleed (filling up the full width of the screen) but the new image from instagram and all the posts are scaled down. I took some screenshots so you can see whats happening. 

@bradfrost is something with the images throwing this off?

![img_1193](https://cloud.githubusercontent.com/assets/4777743/10311564/4e33f23c-6c15-11e5-9328-5caaf7ecbeb8.PNG)
![img_1194](https://cloud.githubusercontent.com/assets/4777743/10311563/4e3122f0-6c15-11e5-919f-a5af74d5064f.PNG)

**Comment by bradfrost** [comment]
@minifrost This is a separate issue, so I'm closing this out and I created a new issue here: #29
