### ISSUE TITLE
press area

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#15]
links to article, magazine, mentions somewhere in about

**Comment by frostyweather** [comment]
Do we want to do the press area like the "Much Love" section of your page Melissa or should we do logos for the site, magazine, or newspaper Frost Finery was featured in?

**Comment by frostyweather** [comment]
Created a rough press area on the site local to my computer. Let me know if this looks alright. Thanks! 
![screen shot 2015-09-28 at 2 54 07 pm](https://cloud.githubusercontent.com/assets/13662843/10145427/01ee7548-65f1-11e5-9dbc-42cf1faecabf.png)

**Comment by bradfrost** [comment]
Looking at this design I think it will need one of the short `<hr />` separators, and it's probably also a good idea to have a little excerpt below the heading (similar to the collection page). Also, I think a single-column layout containing press items in reverse-chronological order would do well. And lastly, I think for the logos we can make them grayscale ([using CSS](https://css-tricks.com/almanac/properties/f/filter/)) in order to give them a bit of consistency.

**Comment by bradfrost** [comment]
And this is a comment for @minifrost, I think it's worth you chiming in here to discuss the content priority on this page. I personally don't think your "thank you" section should be above your press area. Maybe it's worth doing a bit of a design comp to flesh this out?

**Comment by minifrost** [comment]
I hear you... I'll have to figure that out this week. In the meantime here are a few more press clips: 
http://www.pittsburghmagazine.com/Best-of-the-Burgh-Blogs/Gotta-Have-It/July-2015/PA-Pride-Introducing-The-Keystone-Earring/

http://www.post-gazette.com/news/politics-state/2015/04/08/Wolf-says-work-continues-on-state-budget-overhaul/stories/201504080225

**Comment by frostyweather** [comment]
This is the latest press area I have. 
![screen shot 2015-10-05 at 4 05 05 pm](https://cloud.githubusercontent.com/assets/13662843/10292057/0ba9ed58-6b7b-11e5-8865-322461389be8.png)
Just let me know when you get a general idea of the design you want for the order of articles, etc.

**Comment by frostyweather** [comment]
At the bottom of the admin page in Pages>About (right now I only have it locally), you will be able to add and reorder the articles.
![screen shot 2015-10-05 at 4 08 30 pm](https://cloud.githubusercontent.com/assets/13662843/10292136/924f490c-6b7b-11e5-8c78-ae7544eb5e14.png)

**Comment by bradfrost** [comment]
Press area is implemented on the about page
