### ISSUE TITLE
Testimonial Styling

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#16]
somewhere under custom work

**Comment by bradfrost** [comment]
Will need to create a new custom post type with the appropriate custom fields. I'm thinking
- Quote
- Citation (i.e. person's name)
- Quote source URL (if it came from an article, tweet, etc)

**Comment by frostyweather** [comment]
Not sure where to put the testimonial stuff? Was thinking here, but we also don't want the potential customer to have to scroll too much. Any idea @minifrost 
![screen shot 2015-10-05 at 5 23 15 pm](https://cloud.githubusercontent.com/assets/13662843/10294048/ec7ee978-6b85-11e5-94d1-c11d6334a3a4.png)
?

**Comment by frostyweather** [comment]
What it would look like on your actual site...
![screen shot 2015-10-05 at 6 25 32 pm](https://cloud.githubusercontent.com/assets/13662843/10295435/99e0abd0-6b8e-11e5-9a69-15a26569b46a.png)

**Comment by frostyweather** [comment]
Close #16. Testimonials styled and put into Custom Work Page
