### ISSUE TITLE
Add Codepress Admin Columns

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#18]
Implement this: https://wordpress.org/plugins/codepress-admin-columns/

So that on the jewelry admin view, instead of this:

![jewelry frost finery wordpress](https://cloud.githubusercontent.com/assets/383701/9686241/fbac29ae-52f0-11e5-8f12-e79f82f272a5.png)

We'll see all the custom fields (name, price, category, etc)

**Comment by frostyweather** [comment]
Added this and formatted it to be useful. Let me know if you want me to reformat the columns so that it is a better layout for you. Thanks!

**Comment by bradfrost** [comment]
Looks good
