### ISSUE TITLE
Design Detail View for collections

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#19]
This is very relevant: http://blog.cloudfour.com/shifty-tile-flyouts/

We want to display the product info inline within the grid, and the linked technique looks like it fits the bill.

**Comment by frostyweather** [comment]
Added flyout to appear on click for first jewelry image in JS for the Collection page, but couldn't figure out how to make it appear for all of the images on the page. Tried using a for loop and querySelectorAll but couldn't figure out why it kept spitting out an error :  "Uncaught TypeError: jewelryFlyout.addEventListener is not a function." Code is below

flyoutMode = false;
var jewelryFlyout = document.querySelectorAll('.jewelry-item');
jewelryFlyout.addEventListener("click", function(event){
    event.preventDefault();
    for (i = 0; i < jewelryFlyout.length; ++i) {
        if (flyoutMode === false) {
        document.querySelector('.jewelry-panel').style.display = "flex";
        flyoutMode = true;
        }
        else {
            flyoutMode = false;
            document.querySelector('.jewelry-panel').style.display = "none";
        }
    }
});

**Comment by bradfrost** [comment]
I believe this is because `querySelectorAll` returns an array. So you would need to loop through the array and assign the `addEventListener` _inside_ the loop rather than outside of it.

**Comment by frostyweather** [comment]
Flyout works and includes media queries and jewelry panel reposition on window resize
