### ISSUE TITLE
Add box shadow + light gray border

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#24]
<img width="1146" alt="screen shot 2015-09-21 at 11 18 39 pm" src="https://cloud.githubusercontent.com/assets/4777743/10010318/a47aee48-60b7-11e5-898e-9d4c6512522d.png">

Brad played around with the borders and shadows last night and we came up with a good look. Would love to implement this, thanks! :)

**Comment by frostyweather** [comment]
Added the border and box shadow. Please check to see if this works for you Mel. Thanks.

**Comment by frostyweather** [comment]
Close #24
