### ISSUE TITLE
Add way to re-order images in collection

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#25]
It would be great to figure out a way to re-order images within the collection. For example, if I have a hot selling product and want to move it to be the first featured product or there's a product that's not selling and I want to move it to the end.

**Comment by bradfrost** [comment]
This looks promising: https://wordpress.org/plugins/simple-custom-post-order/

**Comment by frostyweather** [comment]
Installed plugin. Changed orderby=> meta_value_num to orderby=>menu_item to make this work on the front end when items are moved around.
