### ISSUE TITLE
Tweaking on Custom Work Page

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#28]
http://frostfinery.com/custom-work/

There's a href tag showing up in the copy at the bottom of the custom work page - can we make sure that's just showing up as copy?

Also is there a way to add a little more white space or padding between where the top bracelet images ends and where the border and new title begins? I think this is also a pattern throughout the site where some negative space would help if that's not a huge task.

Here's a mockup of some added negative space. You might be able to compare it against the live site to see the difference. 
![ff_customwork_mock](https://cloud.githubusercontent.com/assets/4777743/10311977/19926a2a-6c17-11e5-91ac-47937c851f87.jpg)

@bradfrost  not sure if I'm using the right language here in saying "padding" so you might wanna chime in.

**Comment by frostyweather** [comment]
Fixed the a href tag part. Would this be enough white space or is this too much @minifrost ?

![screen shot 2015-10-06 at 11 05 41 am](https://cloud.githubusercontent.com/assets/13662843/10312710/57216992-6c1a-11e5-9e25-0b47d80fdf87.png)

**Comment by frostyweather** [comment]
If you want to add text in between the button and Custom Work Gallery it automatically adds space in between. I can also add more whitespace if needed as well. 
![screen shot 2015-10-06 at 12 38 35 pm](https://cloud.githubusercontent.com/assets/13662843/10315258/33ca0b4a-6c27-11e5-8170-6e0acc42f331.png)

**Comment by minifrost** [comment]
Looking better, maybe not quite as much space. Sorry I know that's a bit ambiguous... Maybe measure the space between the the sunburst and line and the "custom work gallery" then 2x for that negative space area... hope that makes sense.

For the testimonials... maybe they go below the custom work gallery? It would be nice to have a few at the top but a lot of them are pretty long and I'm worried it would push the images down too far. Here is an example of a real testimonial:

"Before we contacted Frost Finery, I was incredibly anxious about the process of shopping for wedding rings. My wife and I both knew we wanted something unique and special, but at the same time, we had no idea what we were looking for. Melissa was an expert at guiding us through the ins-and-outs of the whole process, which made everything fun and easy. When the rings finally came in the mail, everything was absolutely perfect. Working with Frost Finery was probably the easiest part of planning our wedding, and we couldn't be happier with the results."

**Comment by bradfrost** [comment]
@minifrost is it possible to do a little comp to give a better idea of how you'd want this laid out?

**Comment by frostyweather** [comment]
I'm trying to get the testimonials to print out underneath but for some reason it is not working after the grid of jewelry.

**Comment by frostyweather** [comment]
Nevermind. Had to add wp reset query.
![screen shot 2015-10-06 at 7 23 00 pm](https://cloud.githubusercontent.com/assets/13662843/10325478/b30a0706-6c5f-11e5-8dd4-5170c4685e7a.png)

**Comment by bradfrost** [comment]
Closing this out.
