### ISSUE TITLE
Fixed-width images with captions break layout on small screen

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#29]
From @minifrost:

One thing is that on mobile the layout is looking a bit off. The old images are full bleed (filling up the full width of the screen) but the new image from instagram and all the posts are scaled down. I took some screenshots so you can see whats happening. 

@bradfrost is something with the images throwing this off?

![img_1193](https://cloud.githubusercontent.com/assets/4777743/10311564/4e33f23c-6c15-11e5-9328-5caaf7ecbeb8.PNG)
![img_1194](https://cloud.githubusercontent.com/assets/4777743/10311563/4e3122f0-6c15-11e5-919f-a5af74d5064f.PNG)

@frostyweather, this is due to to Wordpress applying an inline style to `.wp-caption`. If you add an `!important` declaration for `.wp-caption` it should fix it.

**Comment by frostyweather** [comment]
Should I add the !important to the max-width or whole class of .wp-caption itself?

**Comment by frostyweather** [comment]
This should work now @bradfrost and @minifrost . You can close this if the problem seems fixed. Thanks!

**Comment by frostyweather** [comment]
Issue has been resolved. Woo!
