### ISSUE TITLE
Add Events

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#3]
From Melissa:

> area for upcoming/past events

This would make most sense to include on the [shop page](http://frostfinery.com/shop/), but can also include the next event in the footer, with a link pointing to all upcoming events.

**Comment by frostyweather** [comment]
Structure is there for the Events page. Go in and add your event information.

Actual Events Page (Frontend): http://frostfinery.com/events/
Admin Page To Post Events (Backend): http://frostfinery.com/wp-admin/edit.php?post_type=events

**Comment by bradfrost** [comment]
@minifrost added upcoming events, but needs to go through and add the others

**Comment by frostyweather** [comment]
Realized the Simple Custom Post Order was set only to jewelry locally which is why the ascending and descending order stuff was not working properly. Events page is finished (with @minifrost updating retroactively).
