### ISSUE TITLE
Fix lazy loading images on Collection Page

### ISSUE THREAD

**Issue by frostyweather** [bradfrost/frost-finery-wp#30]
Fix lag that exists on the collection page. Probably has something to do with all images showing up when page is loaded. Somehow need to figure out how to display none on load.

**Comment by bradfrost** [comment]
The plan of attack will involve a few steps:
1. All of the images inside `.jewelry-gallery` should not have an `src` attribute. Instead, change all `src` attributes to `data-src`. This way the browser won't download all the images that are hidden in the panels on page load.
2. When the user clicks the thumbnail and loads the panel, you'll need to dynamically set the attribute `src` and set the value to the value of `data-src`

**Comment by frostyweather** [comment]
Semi-working. If all thumbnail images of the jewelry load on the page and then you click, this works when you click any item. If all of the images don't load and you click an item for the first time, the panel opens without the gallery in the jewelry panel. Click a second time and the src is added and the images finally show up. Tried changing the order of JS but that didn't do anything either. Still trying to figure it out.

**Comment by frostyweather** [comment]
Fixed image sizes and inserted the JS into the Open Panel function to get the images to show up on the first click. The gospel has been written. Close issue.
