### ISSUE TITLE
Image Compression Help

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#32]
Right now some of the images in the collection page are massive, and the total weight is ending up weighing around 10MB. 

<img width="1280" alt="collection frost finery" src="https://cloud.githubusercontent.com/assets/383701/10398161/0a424a98-6e71-11e5-814d-bccaf76583d9.png">

There are [plugins out there](http://premium.wpmudev.org/blog/10-best-image-optimization-plugins-to-speed-up-your-wordpress-site/) to help reduce image size, and there are some native Wordpress techniques to help with this as well. 

Research and implement some of these techniques so it's not such a big payload.

**Comment by bradfrost** [comment]
These will be helpful:

https://developer.wordpress.org/reference/functions/add_image_size/

http://support.advancedcustomfields.com/forums/topic/custom-image-sizes/

**Comment by frostyweather** [comment]
Installed Regenerate Thumbnails plugin and added "add_image_size( 'jewelry-collection', 400, 400 ); //Collection grid to function page and incorporated it into the block-jewelry section. Issue taken care of.
