### ISSUE TITLE
Refactor About Page

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#33]
In order to take care of the press area (#15) we need to redesign the about page, which I think can really use it. Here's the [current page](http://frostfinery.com/about/):

![about frost finery](https://cloud.githubusercontent.com/assets/383701/10432276/01b9fa74-70d8-11e5-8e18-b15dc902d617.png)

A few suggestions:
- People visiting your about page should first be met with some text like "Frost Finery is a custom jewelry studio based in Pittsburgh, PA. Specializing in hand-made  blah blah..." 
- The order of operations should go something like: Intro copy (mentioned above), Press, Behind the Bench, Process, Thank you's. The reasoning behind this ordering is because first and foremost you need to establish yourself as an established and credible brand. If people are interested and want to learn more about you and your process, they're free to scroll down and learn more.
- Establish a consistent tone of voice. I'd recommend switching out of first person ("I") and using 3rd-person "Frost Finery". The language can change to something like "Frost Finery is the brainchild of Melissa Frost, a Pittsburgh-based blah blah blah" and in the thank you's section: "Frost Finery wouldn't be possible without the help of these wonderful people and organizations:"  
- The layout will follow the other pages rather than the current two-column approach. We'll sepearate each section with a line. This layout means that we could include an image per section if that works for you.

**Comment by minifrost** [comment]
Ok about.psd is in the same _web folder in dropbox as the homepage stuff. 

FrostFinery/_Web/_UPDATES_10.2015/FF_About_10.2015.psd

**Comment by bradfrost** [comment]
New about page is up: http://frostfinery.com/about/
