### ISSUE TITLE
Implement new hero images

### ISSUE THREAD

**Issue by minifrost** [bradfrost/frost-finery-wp#35]
Hey guys,

I created Large, Med and Small screen hero sizes. There are some kinda loose PSD mockups and isolated PSDs of the hero images here:

Dropbox/FrostFinery/_web/_UPDATES_10.2015

I made these pretty fast so they may need a little clean up around the edges, meaning the edges need to be 100% #ffffff white so it seamlessly blends in with the background. Not sure how the text is going to go on there... I was thinking of removing text altogether on the small version or just having the headline so it's not looking too crowded.

Thanks! Let me know if you run into any major roadbloacks!

**Comment by frostyweather** [comment]
I got this stuff working locally @minifrost . We have to clean up the images a little bit since there are shadows and colors that aren't white so it looks like it blends more with the background on the page.

**Comment by minifrost** [comment]
how do I view it locally?

**Comment by bradfrost** [comment]
Might be worth uploading some screenshots Ian

On Wednesday, October 21, 2015, Melissa Frost notifications@github.com
wrote:

> how do I view it locally?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bradfrost/frost-finery-wp/issues/35#issuecomment-150051006
> .

## 

---

Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by frostyweather** [comment]
You should be able to view it on the computer I use in the office. The URL is frostfinery:8888 if it isn't open. If you can wait tomorrow, I'll show you then since I didn't bring the computer home.

**Comment by frostyweather** [comment]
Added images to hero. Up to @minifrost to tweak or put in new images if desired. Close #35
