### ISSUE TITLE
Add Stores

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#4]
From Melissa:

>  adding an area for stockists (jack+Jules, shop in EL) to the contact section

The site will need to display the information for the stores where her jewelry can be found. Melissa says the contact page, but I think it would make more sense under the [shop](http://frostfinery.com/shop/) page. 

We can also either include the store contact info on the contact page, or simply link to the shop page.

**Comment by bradfrost** [comment]
@frostyweather set up the fields to add the shops. @minifrost can you populate the shops so that we can work on the frontend? Here's the link: http://frostfinery.com/wp-admin/post-new.php?post_type=shops

**Comment by frostyweather** [comment]
Added the stores, upcoming events, and past events to the "Shop" page locally. Didn't want to launch this just in case. Here's a screenshot. 
![screen shot 2015-09-24 at 8 59 02 pm](https://cloud.githubusercontent.com/assets/13662843/10090581/2a11cca4-62ff-11e5-90b5-a90f196bcb2f.png)

**Comment by bradfrost** [comment]
Looking good for the most part. We don't need past events in there, but perhaps a "See all events" link would make sense there. Also, it would be a good idea to have the intro text for each section (similar to the section intro text on collections/archives) beneath each heading. That way @minifrost can add a little intro text.

**Comment by frostyweather** [comment]
The Shop Page is now active. Please update the copy, Melissa, under Pages>Shop. The event title and event excerpt are for the left column and the shop title and shop excerpt are for the left column. Thanks!

**Comment by minifrost** [comment]
I haven't delivered jewelry to Rosewood Boutique yet and it probably won't happen until the end of Oct so I'll update later. One change tho... I wasn't sure how to update the copy... but can I change the title of "shops carrying frost finery" to just "stockists"

**Comment by frostyweather** [comment]
Sure thing. I'll change that. For the future, to change the column title for shops go to all Pages, All Pages, Shop, then change the "Shop Title." It's under actual pages and not the custom field "Shops" (Sort of confusing I know)

**Comment by bradfrost** [comment]
This looks like it has been taken care of. Closing this out.
