### ISSUE TITLE
List Styles

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#42]
<img width="1280" alt="about frost finery" src="https://cloud.githubusercontent.com/assets/383701/10708797/b2ac03a0-79e2-11e5-806a-a7149acf29f2.png">

Unfortunately it looks like the list styles still got wiped out. Can you bring back the three-column pink links?

**Comment by frostyweather** [comment]
This should work now. Also learned that Gruntfile.js is a great and terrible thing
