### ISSUE TITLE
Remove email newsletter form from footer

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/frost-finery-wp#9]
@minifrost, @frostyweather and I are discussing how it would be helpful to display the next upcoming event in the footer of the website. In order to make room for this, I think it would be a good idea to remove the newsletter signup form from the footer. Currently there are 3 people signed up for the newsletter, and given how busy you are it doesn't seem like you're in a position to operate the newsletter. So I think it would be a good idea to remove it and replace it with the next upcoming event. Thoughts?

**Comment by bradfrost** [comment]
We'll replace that with the next upcoming event

**Comment by frostyweather** [comment]
Added the next event section to the footer. Melissa ended up wanting the newsletter in the footer, so we kept that. Taken care of overall.
